[package]
name = "myq2-common"
version = "1.0.0"
edition = "2021"

[dependencies]
rand = "0.8"
crc = "3"
md4 = "0.10"
bitflags = "2"
rayon = { workspace = true }
parking_lot = { workspace = true }
crossbeam = { workspace = true }
flate2 = { workspace = true }
